AWSTemplateFormatVersion: 2010-09-09

Description: This template creates an RDS database with MariaDB 10.6.5 engine 

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - 
        Label: 
          default: Export VPC Stack Name
        Parameters:
          - ExportVpcStackName
      - 
        Label: 
          default: Database Parameters
        Parameters:
          - DatabaseInstanceIdentifier
          - DatabaseName
          - DatabaseUser
          - DatabaseBackupRetentionPeriod
          - DatabaseAllocatedStorage
          - DatabaseInstanceClass
          - MultiAZDatabase

Parameters:
  ExportVpcStackName:
    Description: The name of the vpc stack that exports values
    Type: String

  DatabaseInstanceIdentifier:
    Description: Instance identifier name
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters
    Default: mariadb01    
    MaxLength: 60
    MinLength: 1
    Type: String

  DatabaseName:
    Description: MariaDB database name
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters
    Default: applicationdb    
    MaxLength: 64
    MinLength: 1
    Type: String

  DatabaseUser:
    Description: Username for MariaDB database access
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters
    Default: dbadmin    
    MaxLength: 16
    MinLength: 1
    Type: String

  DatabaseBackupRetentionPeriod:
    Description: The number of days for which automatic DB snapshots are retained
    ConstraintDescription: Database backup retention period must be between 0 and 35 days
    Default: 0    
    MaxValue: 35
    MinValue: 0
    Type: Number

  DatabaseAllocatedStorage:
    Description: The size of the database (Gb)
    ConstraintDescription: Must be between 5 and 1024Gb
    Default: 20    
    MaxValue: 65536
    MinValue: 5
    Type: Number

  DatabaseInstanceClass:
    Description: The database instance type
    AllowedValues:
      - db.t2.micro
      - db.t3.micro      
    ConstraintDescription: Must select a valid database instance type
    Default: db.t2.micro    
    Type: String

  MultiAZDatabase:
    Description: Creates a Multi-AZ MariaDB Amazon RDS database instance
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be either true or false
    Default: false    
    Type: String

Resources:   
# Creates the Database Subnet Group  
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS database
      SubnetIds: 
        - Fn::ImportValue: !Sub PrivateSubnet2 
        - Fn::ImportValue: !Sub PrivateSubnet3        
      Tags:
        - Key: Name
          Value: database subnets

# Creates the Database Instance   
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref DatabaseAllocatedStorage
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      BackupRetentionPeriod: !Ref DatabaseBackupRetentionPeriod
      DBInstanceClass: !Ref DatabaseInstanceClass
      DBInstanceIdentifier: !Ref DatabaseInstanceIdentifier
      DBName: !Ref DatabaseName
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      Engine: MariaDB
      EngineVersion: 10.6.5
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: '{{resolve:ssm-secure:RDSpass:1}}'
      MultiAZ: !Ref MultiAZDatabase
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub DatabaseSecurityGroup